spring.application.name=ddeonabom
spring.devtools.restart.enabled=true

#oracle 연결
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.profiles.active=local
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


#타임리프 설정
spring.thymeleaf.cache=false

#mybatis
#파일 만들면 주석 풀기
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=kh.ddeonabom.*.model.vo, kh.ddeonabom.*.*.model.vo
mybatis.configuration.jdbc-type-for-null=null

server.servlet.session.timeout=20m


#g메일
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saundayy@gmail.com
spring.mail.password=wexk jsvn tbwc spyr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=saundayy@gmail.com

spring.config.import=optional:application-local.properties

# 파일 업로드 용량 제한 확대
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

#aws
cloud.aws.credentials.access-key={엑세스키}
cloud.aws.credentials.secret-key={시크릿키}
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false
cloud.aws.s3.bucket=

tourapi.key=

tourapi.base-url=

kakao.mobility.rest-key=

kakao.api.key=

server.port=8080
